### ISSUE TITLE
Some bug in the code.

### ISSUE THREAD

**Issue by nivi1501** [DRAMA-technion/DRAMA#1]
Hi, 
I am facing the following issue while executing the code. Please let me know how to resolve this
python3 scale.py -arch_config=configs/google.cfg -network=topologies/conv_nets/yolo.csv 
Using Architechture from  configs/google.cfg
====================================================
******************* SCALE SIM **********************
====================================================
Array Size: 	256x256
SRAM IFMAP: 	8192
SRAM Filter: 	8192
SRAM OFMAP: 	8192
CSV file path: 	topologies/conv_nets/yolo.csv
Dataflow: 	Output Stationary
====================================================

Commencing run for Conv1
Generating traces and bw numbers
100%|████████████████████████████████████████████████████████████████████████████████████| 2067604/2067604 [01:29<00:00, 23150.25it/s]
Traceback (most recent call last):
  File "scale.py", line 209, in <module>
    app.run(main)
  File "/home/nivedita/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/nivedita/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "scale.py", line 206, in main
    s.run_scale()
  File "scale.py", line 94, in run_scale
    self.run_once()
  File "scale.py", line 122, in run_once
    r.run_net(  ifmap_sram_size  = int(self.isram_min),
  File "/home/nivedita/Documents/CompressionCNN/DRAMA-main/DRAMA+ScaleSim/run_nets.py", line 87, in run_net
    tg.gen_all_traces(  array_h = array_h,
  File "/home/nivedita/Documents/CompressionCNN/DRAMA-main/DRAMA+ScaleSim/trace_gen_wrapper.py", line 103, in gen_all_traces
    bridge = br.Bridge(
  File "/home/nivedita/Documents/CompressionCNN/DRAMA-main/DRAMA+ScaleSim/bridge.py", line 16, in __init__
    self.numChannels = int(config.get(dram_sec, 'NumberOfChannels').strip())
  File "/home/nivedita/anaconda3/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/home/nivedita/anaconda3/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'dram_presets'
Exception ignored in: <function Bridge.__del__ at 0x7f5d46ff2d30>
Traceback (most recent call last):
  File "/home/nivedita/Documents/CompressionCNN/DRAMA-main/DRAMA+ScaleSim/bridge.py", line 78, in __del__
AttributeError: 'Bridge' object has no attribute 'ifmap_file'

**Comment by ori-sch** [comment]
The google.cfg is missing the section dram_presets
There are examples of how to set it correctly under test.cfg (sizes are in log2, for example "numberOfBanks: 2" means that there are 8 banks)
